public class dayTwoTwo {
    public static void main(String[] args) throws Exception {
        int[] prvnici = {6, 10, 16, 2, 3, 2, 13, 1, 4, 15, 11, 1, 5, 8, 1, 13, 6, 10, 5, 2, 9, 2, 12, 13, 3, 12, 2, 17, 3, 3, 18, 12, 17, 9, 7, 5, 3, 5, 3, 6, 4, 2, 6, 4, 2, 6, 9, 8, 6, 7, 6, 8, 1, 2, 13, 2, 16, 3, 3, 2, 10, 7, 8, 11, 2, 8, 4, 11, 9, 16, 12, 5, 4, 1, 2, 1, 8, 5, 5, 2, 2, 12, 1, 8, 9, 2, 17, 9, 18, 5, 2, 14, 3, 1, 1, 7, 11, 15, 6, 4, 5, 8, 6, 1, 5, 4, 1, 3, 2, 3, 1, 2, 1, 12, 6, 10, 1, 18, 1, 1, 8, 1, 7, 4, 11, 12, 11, 15, 3, 2, 5, 3, 10, 8, 7, 8, 5, 2, 2, 9, 8, 2, 8, 13, 1, 8, 16, 5, 5, 10, 10, 12, 2, 2, 1, 12, 10, 2, 4, 1, 4, 11, 12, 5, 3, 5, 9, 8, 5, 1, 7, 2, 4, 6, 1, 4, 2, 2, 17, 13, 5, 5, 4, 1, 11, 3, 7, 1, 2, 1, 6, 4, 7, 9, 5, 12, 5, 2, 5, 13, 1, 1, 3, 15, 7, 10, 1, 3, 11, 6, 4, 2, 7, 5, 5, 4, 13, 3, 2, 5, 3, 6, 12, 2, 5, 4, 1, 3, 7, 2, 4, 18, 5, 17, 2, 2, 5, 4, 5, 10, 9, 4, 4, 3, 1, 7, 2, 3, 3, 3, 7, 15, 1, 1, 3, 3, 13, 4, 3, 10, 4, 6, 11, 9, 7, 8, 3, 1, 7, 8, 11, 12, 3, 7, 9, 11, 1, 7, 7, 7, 5, 3, 13, 11, 4, 3, 3, 7, 8, 8, 5, 15, 12, 2, 6, 7, 9, 6, 3, 2, 8, 1, 8, 6, 16, 1, 2, 8, 12, 2, 2, 7, 8, 1, 1, 5, 6, 5, 3, 5, 4, 13, 4, 16, 8, 5, 6, 19, 10, 4, 15, 9, 4, 3, 3, 6, 5, 5, 5, 5, 1, 6, 3, 5, 10, 2, 6, 4, 5, 2, 8, 12, 2, 2, 3, 6, 8, 4, 1, 7, 2, 3, 3, 10, 2, 1, 13, 9, 1, 3, 18, 12, 8, 3, 7, 2, 1, 3, 3, 4, 8, 8, 5, 4, 6, 3, 4, 9, 14, 8, 4, 12, 8, 4, 8, 13, 6, 1, 2, 5, 6, 1, 3, 3, 5, 6, 3, 4, 3, 5, 5, 5, 1, 3, 2, 9, 1, 8, 4, 10, 8, 4, 11, 2, 3, 8, 4, 1, 2, 3, 3, 9, 1, 10, 4, 4, 4, 3, 3, 6, 5, 4, 3, 6, 3, 4, 11, 15, 5, 3, 2, 4, 11, 13, 6, 5, 7, 1, 10, 4, 14, 3, 16, 2, 1, 6, 3, 2, 2, 1, 14, 4, 4, 1, 1, 2, 12, 3, 1, 10, 5, 15, 12, 5, 9, 7, 11, 1, 14, 1, 13, 5, 2, 4, 3, 8, 16, 3, 2, 3, 3, 6, 5, 2, 1, 3, 4, 12, 1, 2, 4, 7, 7, 9, 6, 6, 4, 13, 1, 8, 14, 5, 3, 1, 4, 3, 3, 2, 7, 10, 8, 2, 2, 8, 11, 16, 2, 18, 9, 3, 5, 2, 4, 15, 15, 2, 7, 3, 9, 14, 4, 1, 3, 4, 6, 7, 3, 13, 6, 7, 3, 11, 7, 2, 4, 9, 3, 11, 6, 1, 3, 16, 3, 11, 5, 4, 7, 7, 11, 1, 3, 1, 3, 8, 3, 7, 6, 3, 10, 3, 6, 14, 15, 2, 2, 5, 11, 3, 16, 5, 1, 1, 1, 2, 14, 2, 16, 1, 8, 2, 4, 6, 12, 15, 13, 18, 2, 11, 1, 3, 3, 1, 1, 4, 7, 6, 7, 3, 8, 3, 12, 5, 1, 1, 19, 2, 13, 5, 2, 16, 2, 6, 1, 11, 6, 5, 2, 9, 1, 2, 1, 1, 4, 2, 6, 7, 3, 13, 8, 6, 6, 9, 3, 7, 3, 13, 1, 5, 1, 7, 3, 11, 1, 11, 1, 8, 1, 2, 6, 2, 3, 10, 6, 1, 6, 1, 5, 3, 6, 6, 7, 2, 4, 15, 1, 5, 5, 1, 2, 2, 7, 5, 3, 5, 10, 9, 6, 3, 10, 15, 16, 6, 1, 5, 4, 15, 2, 14, 9, 1, 3, 8, 1, 5, 1, 2, 10, 8, 13, 1, 9, 9, 2, 14, 9, 5, 3, 2, 9, 1, 2, 17, 2, 17, 5, 1, 4, 6, 13, 3, 1, 5, 6, 1, 2, 4, 2, 9, 9, 9, 6, 8, 3, 3, 7, 10, 1, 9, 3, 3, 11, 3, 3, 11, 14, 14, 1, 6, 4, 10, 6, 14, 1, 6, 13, 3, 4, 16, 1, 9, 4, 13, 16, 13, 8, 9, 7, 3, 15, 6, 3, 6, 3, 12, 3, 12, 4, 2, 1, 1, 14, 10, 17, 1, 5, 2, 5, 2, 2, 6, 8, 3, 7, 1, 8, 5, 10, 9, 8, 19, 16, 12, 2, 3, 1, 4, 9, 3, 11, 2, 12, 4, 10, 3, 3, 3, 2, 14, 16, 5, 4, 10, 1, 9, 13, 2, 10, 6, 3, 3, 7, 1, 10, 3, 8, 4, 1, 3, 7, 9, 1, 2, 8, 6, 13, 6, 15, 1, 3, 7, 5, 2, 4, 5, 1, 9, 4, 8, 1, 2, 7, 10, 14, 7, 11, 2, 5, 6, 4, 17, 7, 1, 5, 10, 4, 9, 2, 1, 6, 12, 4, 1, 5, 13, 7, 15, 7, 7, 11, 12, 5, 17, 4, 1, 5, 1, 14, 12, 7, 6, 1, 1, 16, 7, 3, 10, 8, 2, 8, 4, 2, 6, 2, 7, 17, 18, 4, 1, 1, 4, 1, 9, 3, 12, 8, 2, 3, 4, 5, 4, 3, 6, 2, 6, 2, 6, 1, 2, 3, 1, 10, 3, 5, 6, 5, 8, 3, 1, 17, 5, 7, 1, 3, 1, 4, 3, 3, 1, 4, 7, 5, 1, 8, 2, 6, 19, 4, 12, 6, 1};
        int[] druzici = {7, 12, 17, 4, 4, 10, 19, 3, 6, 17, 12, 7, 6, 12, 8, 16, 9, 11, 7, 4, 15, 3, 13, 15, 10, 16, 6, 18, 5, 6, 19, 13, 18, 19, 11, 8, 6, 11, 4, 9, 5, 4, 7, 9, 4, 13, 15, 11, 11, 13, 8, 11, 5, 3, 16, 3, 17, 4, 4, 4, 11, 12, 9, 20, 4, 13, 10, 15, 10, 17, 14, 17, 6, 4, 3, 6, 11, 10, 6, 6, 5, 15, 3, 14, 12, 3, 18, 10, 20, 7, 13, 17, 9, 6, 3, 19, 17, 18, 9, 5, 12, 9, 8, 6, 6, 8, 7, 4, 5, 15, 4, 4, 6, 14, 11, 12, 6, 19, 3, 3, 10, 9, 9, 17, 13, 14, 15, 16, 4, 8, 6, 7, 17, 9, 9, 11, 16, 3, 10, 10, 9, 3, 13, 18, 3, 13, 18, 7, 10, 11, 12, 13, 4, 5, 4, 16, 11, 17, 5, 2, 5, 12, 13, 15, 5, 14, 20, 9, 6, 13, 8, 3, 8, 11, 3, 6, 8, 7, 18, 17, 11, 14, 7, 6, 13, 11, 8, 4, 5, 3, 7, 5, 14, 10, 12, 14, 6, 7, 8, 15, 8, 2, 18, 16, 12, 11, 2, 4, 12, 7, 6, 4, 9, 6, 11, 5, 16, 5, 7, 6, 5, 14, 13, 3, 6, 5, 8, 4, 13, 17, 6, 19, 11, 18, 19, 7, 11, 5, 6, 11, 11, 5, 5, 4, 9, 9, 8, 5, 6, 4, 17, 16, 11, 5, 5, 9, 17, 5, 4, 12, 9, 7, 14, 11, 8, 12, 5, 4, 8, 16, 14, 14, 4, 9, 10, 16, 4, 8, 8, 8, 9, 9, 18, 17, 12, 5, 13, 9, 9, 14, 6, 16, 13, 4, 13, 8, 10, 14, 12, 7, 9, 4, 10, 7, 19, 4, 3, 11, 18, 7, 3, 11, 17, 7, 6, 11, 7, 6, 8, 15, 5, 15, 8, 17, 11, 6, 8, 20, 15, 5, 16, 11, 5, 8, 9, 10, 6, 6, 6, 7, 6, 9, 4, 8, 12, 11, 8, 7, 7, 7, 19, 15, 3, 4, 4, 7, 9, 11, 2, 9, 3, 5, 7, 17, 6, 3, 16, 10, 3, 11, 19, 13, 13, 8, 17, 6, 4, 4, 4, 7, 11, 10, 7, 6, 7, 7, 19, 11, 16, 10, 5, 14, 12, 5, 10, 15, 7, 13, 4, 17, 15, 9, 4, 8, 7, 12, 4, 5, 4, 6, 6, 15, 8, 4, 3, 10, 5, 9, 5, 12, 11, 5, 14, 4, 7, 10, 10, 9, 4, 6, 6, 10, 4, 18, 5, 5, 5, 12, 5, 10, 18, 5, 4, 11, 6, 12, 12, 20, 6, 4, 3, 6, 16, 15, 7, 6, 9, 10, 13, 5, 20, 5, 19, 4, 8, 11, 4, 14, 4, 7, 16, 5, 7, 5, 5, 3, 13, 13, 11, 12, 7, 18, 17, 13, 11, 10, 12, 9, 17, 2, 15, 7, 6, 12, 4, 9, 17, 4, 4, 5, 4, 8, 7, 9, 8, 10, 5, 14, 9, 4, 5, 8, 17, 12, 9, 8, 10, 18, 5, 9, 16, 6, 4, 11, 9, 5, 5, 4, 8, 18, 13, 6, 12, 12, 14, 17, 8, 19, 11, 5, 6, 4, 5, 17, 19, 5, 9, 4, 10, 15, 5, 4, 18, 5, 9, 11, 5, 15, 11, 8, 7, 12, 8, 6, 5, 11, 10, 14, 8, 6, 6, 17, 4, 12, 8, 7, 8, 8, 12, 2, 5, 4, 5, 9, 8, 9, 11, 5, 11, 4, 7, 15, 16, 7, 3, 7, 15, 8, 18, 7, 4, 3, 11, 4, 16, 16, 17, 5, 9, 6, 5, 11, 13, 16, 15, 19, 11, 14, 4, 4, 5, 5, 12, 7, 9, 9, 11, 5, 10, 4, 17, 6, 2, 3, 20, 9, 16, 11, 8, 17, 3, 7, 7, 12, 7, 8, 17, 14, 4, 4, 10, 4, 6, 3, 7, 14, 4, 15, 12, 14, 19, 11, 6, 12, 6, 15, 4, 15, 4, 9, 4, 13, 8, 12, 3, 13, 5, 5, 16, 3, 4, 11, 11, 9, 10, 6, 8, 12, 12, 8, 12, 5, 14, 16, 4, 13, 18, 2, 6, 6, 10, 6, 8, 6, 13, 18, 7, 4, 12, 18, 17, 10, 7, 6, 13, 19, 8, 15, 11, 13, 12, 12, 6, 9, 4, 10, 14, 11, 15, 14, 13, 15, 13, 18, 13, 6, 4, 5, 12, 3, 8, 19, 7, 18, 6, 2, 6, 9, 15, 5, 6, 13, 10, 3, 3, 6, 3, 10, 11, 12, 14, 9, 6, 4, 13, 13, 4, 13, 4, 8, 16, 8, 10, 13, 15, 17, 9, 10, 5, 14, 9, 17, 8, 12, 14, 4, 5, 18, 4, 10, 16, 16, 18, 16, 11, 17, 14, 6, 16, 9, 4, 8, 6, 16, 7, 15, 6, 11, 3, 3, 15, 12, 20, 5, 6, 5, 6, 4, 10, 7, 11, 5, 11, 2, 10, 6, 12, 10, 10, 20, 18, 17, 6, 4, 5, 8, 10, 5, 12, 9, 15, 6, 11, 10, 4, 4, 5, 20, 17, 6, 7, 15, 4, 19, 14, 4, 17, 11, 5, 9, 9, 2, 18, 4, 10, 7, 10, 11, 8, 10, 5, 4, 12, 10, 16, 12, 16, 2, 5, 8, 8, 4, 5, 8, 2, 13, 5, 9, 2, 17, 9, 14, 15, 8, 15, 4, 10, 7, 10, 18, 8, 3, 10, 14, 9, 18, 5, 11, 8, 16, 6, 3, 11, 16, 8, 19, 13, 9, 13, 18, 6, 18, 14, 2, 9, 3, 19, 14, 16, 17, 6, 10, 19, 9, 10, 18, 11, 14, 10, 6, 3, 20, 4, 14, 18, 19, 7, 8, 2, 6, 7, 12, 9, 19, 9, 3, 5, 5, 7, 6, 5, 8, 3, 7, 3, 13, 5, 8, 5, 3, 14, 7, 6, 7, 8, 9, 4, 4, 18, 8, 10, 10, 7, 3, 5, 4, 5, 4, 13, 8, 6, 5, 14, 7, 7, 20, 15, 15, 10, 18};
        String[] pismenci = {"w", "q", "d", "q", "q", "m", "s", "l", "h", "l", "n", "p", "t", "g", "g", "x", "m", "b", "m", "c", "f", "k", "s", "d", "g", "x", "g", "b", "c", "x", "h", "h", "c", "h", "c", "x", "n", "z", "v", "t", "h", "c", "w", "g", "c", "r", "f", "t", "m", "c", "v", "h", "k", "v", "z", "k", "h", "c", "s", "r", "d", "c", "b", "b", "m", "w", "t", "k", "k", "b", "h", "z", "s", "j", "b", "k", "d", "w", "t", "l", "k", "l", "d", "b", "z", "w", "z", "p", "r", "x", "s", "l", "t", "b", "r", "h", "g", "b", "b", "r", "n", "p", "h", "t", "g", "q", "q", "z", "w", "k", "z", "h", "q", "p", "k", "f", "m", "z", "g", "c", "z", "s", "j", "h", "n", "j", "q", "h", "w", "n", "k", "l", "t", "k", "d", "m", "s", "k", "m", "k", "l", "h", "h", "k", "t", "s", "v", "j", "c", "k", "g", "n", "c", "b", "m", "s", "x", "z", "j", "t", "k", "n", "x", "j", "w", "l", "z", "x", "m", "x", "r", "r", "q", "g", "k", "c", "d", "b", "p", "d", "z", "z", "n", "l", "f", "v", "b", "s", "w", "k", "v", "n", "w", "b", "t", "j", "h", "h", "n", "p", "s", "p", "k", "w", "d", "r", "t", "n", "k", "m", "r", "k", "t", "t", "v", "m", "r", "t", "x", "q", "g", "g", "q", "r", "n", "w", "h", "k", "s", "r", "q", "m", "m", "j", "s", "g", "n", "r", "n", "b", "j", "v", "s", "n", "r", "h", "d", "b", "j", "q", "s", "x", "f", "r", "k", "f", "q", "r", "c", "d", "k", "q", "v", "b", "z", "z", "m", "d", "w", "h", "l", "w", "g", "q", "q", "s", "g", "m", "d", "d", "w", "r", "z", "p", "z", "l", "p", "m", "j", "d", "b", "d", "t", "r", "g", "m", "f", "d", "b", "z", "f", "f", "h", "k", "n", "g", "k", "q", "w", "t", "w", "g", "p", "p", "z", "m", "s", "r", "k", "w", "p", "z", "f", "g", "v", "r", "f", "m", "c", "j", "m", "l", "r", "m", "x", "q", "h", "c", "w", "v", "c", "f", "q", "m", "q", "x", "f", "w", "t", "x", "p", "x", "l", "s", "w", "m", "f", "s", "z", "m", "r", "v", "f", "p", "d", "d", "c", "x", "q", "v", "w", "g", "x", "m", "d", "c", "b", "m", "v", "t", "b", "j", "x", "p", "n", "d", "x", "q", "r", "k", "m", "b", "m", "j", "g", "d", "m", "p", "z", "v", "m", "p", "v", "j", "w", "v", "d", "m", "g", "m", "t", "w", "d", "f", "z", "z", "v", "g", "k", "f", "x", "q", "k", "c", "r", "r", "s", "l", "v", "p", "l", "v", "d", "n", "l", "x", "w", "w", "g", "r", "t", "f", "p", "d", "x", "t", "m", "c", "t", "n", "x", "v", "q", "j", "q", "j", "n", "z", "q", "q", "v", "z", "s", "k", "t", "s", "b", "r", "z", "h", "v", "p", "b", "b", "d", "g", "d", "n", "c", "n", "z", "z", "m", "x", "r", "b", "q", "h", "l", "f", "f", "h", "q", "k", "r", "p", "c", "r", "g", "z", "p", "q", "n", "z", "s", "z", "w", "s", "k", "t", "q", "p", "c", "l", "j", "l", "d", "m", "k", "b", "d", "p", "x", "w", "v", "x", "k", "c", "h", "n", "w", "b", "z", "s", "d", "x", "l", "c", "l", "n", "k", "l", "m", "k", "h", "n", "k", "c", "d", "h", "m", "m", "m", "p", "s", "q", "w", "v", "z", "d", "h", "m", "x", "h", "x", "t", "j", "x", "w", "n", "n", "f", "v", "r", "m", "x", "t", "d", "k", "d", "r", "d", "k", "x", "s", "k", "h", "x", "z", "w", "w", "x", "g", "k", "c", "s", "j", "h", "t", "v", "c", "p", "c", "t", "w", "q", "w", "m", "r", "k", "b", "t", "j", "l", "j", "z", "n", "n", "n", "g", "d", "s", "s", "z", "v", "b", "s", "x", "n", "j", "j", "j", "t", "b", "p", "v", "m", "f", "h", "k", "z", "c", "n", "b", "p", "t", "v", "p", "d", "m", "b", "b", "z", "r", "t", "d", "s", "x", "x", "w", "c", "g", "h", "n", "z", "c", "d", "t", "r", "d", "w", "n", "g", "b", "b", "f", "r", "f", "s", "t", "l", "g", "v", "p", "p", "v", "g", "s", "z", "r", "b", "f", "d", "k", "n", "f", "t", "f", "r", "f", "f", "j", "j", "r", "c", "v", "k", "q", "p", "d", "n", "p", "v", "l", "t", "x", "p", "g", "j", "w", "l", "x", "q", "l", "k", "d", "l", "r", "x", "c", "m", "t", "d", "j", "h", "b", "z", "d", "q", "w", "h", "w", "f", "c", "f", "b", "x", "v", "k", "m", "b", "k", "l", "m", "k", "k", "w", "b", "n", "b", "f", "h", "p", "g", "c", "f", "f", "j", "f", "m", "c", "w", "c", "s", "s", "j", "q", "f", "d", "d", "x", "p", "m", "p", "v", "f", "z", "m", "z", "b", "v", "f", "x", "c", "c", "t", "w", "r", "r", "t", "w", "c", "h", "j", "k", "b", "h", "l", "z", "w", "b", "x", "n", "b", "b", "x", "z", "d", "r", "v", "m", "j", "t", "b", "f", "d", "n", "x", "c", "w", "h", "z", "h", "c", "j", "z", "t", "g", "c", "f", "r", "h", "n", "j", "b", "n", "j", "c", "g", "l", "c", "q", "j", "q", "q", "z", "g", "j", "q", "n", "b", "b", "z", "p", "q", "f", "j", "c", "p", "g", "b", "m", "w", "b", "q", "r", "k", "l", "x", "s", "m", "l", "z", "l", "v", "z", "d", "s", "c", "h", "n", "p", "b", "q", "m", "g", "f", "h", "c", "p", "g", "f", "v", "b", "r", "h", "n", "q", "r", "z", "q", "g", "w", "b", "h", "d", "p", "k", "z", "x", "f", "v", "r", "z", "n", "n", "n", "l", "p", "c", "x", "v", "k", "c", "v", "s", "h", "j", "w", "b", "x", "t", "f", "m", "z", "c", "v", "k", "x", "r", "r", "l", "l", "c", "t", "n", "l", "k", "d", "c", "m", "x", "r", "r", "c", "b", "s", "l", "b", "c", "k", "h", "k", "q", "l", "r", "v", "p", "x", "b", "j", "r", "w", "b", "r", "m", "t", "c", "j", "r", "r", "q", "t", "n", "l", "c", "d", "q", "t", "c"};
        String[] asswordi = {"wwhmzwtwwk", "qqqqqqqqqqqdqqq", "ddddgdddddkddddsxddd", "shbqwqpps", "qkfq", "bkdrmcfdhmr", "blccvhsgsnsssqszssm", "qlxllhl", "hhhqhhh", "jrtllrlllllmmlllg", "bnzlnnnnbnntnnnc", "pppvppjppmptp", "tttnht", "glbnlqgggjkh", "dvgsggngg", "xxxzxxxxxxnxjxxxx", "ffmwhxxsm", "bclbkkxblbbb", "mtmmbmmm", "cdgdkcd", "ffffffffpfffffbffff", "kkkqk", "ssssssssssssgs", "ddddddddddddcdqd", "vpgqrvqnlpgjd", "zrrxjxvvrcnkwklddm", "lgjwpg", "bblsjbkrbbbrknmgbx", "ccpmcsvfxlhgbgccccxw", "zsxrhxnptxtwwbbb", "hhhhhhhhhhhhhhhhhcbl", "hhlhnqdhttwhqcwdd", "cccccccccczcccccfcc", "shhhbhhhhtwhkhnbhfp", "tntwmfzdncchszl", "pxmkxmzbbvfldpwc", "rmwnqnlt", "zzhzkzzzzzq", "vwvdb", "ttttctttb", "hhbzc", "cccpccmpcp", "wwwwwhwwj", "qgbwsqlgg", "cddc", "bqxjlrdrgdjlhcpqp", "qqflwbjgffwfxkv", "txtstwzrggtcrtttmpp", "mmmmmlmmrmmmm", "ccsbbcccmckpzrsncbvz", "vvdvdrvkv", "mhhhvshhthhhhtmshhh", "ckkkkk", "nhvvqnvlz", "zzzzzzzzzzzzzzzfz", "gkrj", "hhhhhhhhmghhhhhhrh", "cccs", "ssssssssss", "rlrg", "ddwdddddddz", "pllhkcgrkmcmxqwccclv", "bbbbbbbbg", "bbdbbrbmjbbbxsbgzbsm", "mmqmmfthp", "fwgjkfwwfcbpwbh", "tttttttttqtt", "pkbmgkkkkkrkkkkkkpkk", "mkkkkkkkkg", "bbbbbbbbbbbbbvbbt", "hhhhhhhhhhhphhhhhh", "knzcjlgjlkvglrsqzwt", "vwpjsds", "jjqgnqq", "bbhb", "kgkkkkkvjkkkgjkk", "dddddddnddd", "hdbcwwqltq", "tttttttt", "lllllqlllclgltllj", "kjkkckkhdkkkn", "llvlllllllljplw", "ddnddddcdd", "vbdbfbhsjbbgbpsbq", "zzzzzzzzxzzzz", "swmt", "pfpzprvxdzvkzzhxpz", "lpqppppspjprmppnp", "rrhrxrwkrfrrhgkmftrr", "ppkbxxp", "skqtnddznmqlsjfn", "cdlkcxpvjghdnlllqt", "pttlpbdhtvtkjgh", "zbbbbv", "vrqr", "hhhhhhqhhhhhhhhhhhsh", "gfgmsggzggpgbgggggg", "btzwbbpbsbmvrbbjncb", "bbvbcxxbbbprbbbcxqvp", "kqrhh", "ncnnnmnnmnnf", "nnmmbqcprcbppzgdjft", "hhrhhjhh", "ltjmrtttttnzjtcttv", "gvgwgkgg", "znlthvfskq", "qpqdrzq", "xsqztkz", "bwwwrjww", "kkrkkkkkkkkkkkpkk", "pzbzztkv", "nhbg", "hwntnqpwhcqknpfkqn", "ppdhllppptjcgp", "kkkkktkkkkkk", "fjffzrfqffcfzfcf", "lzmmmz", "zzzzzzzztzzswzzzgxzz", "ggbfxgg", "xgcwxmtzjvlcp", "zzlzzzpbzdzz", "qpsskgwsssvksfvxsss", "tqxjtjddjjjjjjh", "xhhfhhhhhhthhhhhhhh", "nnnnnnnnnnsnnnnnnn", "jxjjjjjjjjljjd", "qnprkqtqcntttqqwgqx", "hhhhhhhhhhhhhhbhh", "wwtw", "wqnnmngnnjnnnnv", "xbkrklb", "lrvlrlllfhslsl", "fhltmsgptmhckrvkttzs", "kkkkkkkxd", "dddddfddddkd", "mgdmmmmmmprmmm", "ssssmsssssssssssssx", "kkmk", "mfmmmmmlcmjwm", "kkkkkkkkxkk", "jkzdnljrlgnf", "vdhlhpcdsh", "hhhhhhhphhhhhhhh", "kkrkkxkkkkkkrpkkkkk", "rttptklrtvtp", "jhssbsssssslb", "zpfwlvcdbjpcxfhvtlrv", "jfmjljj", "cgctckffldkcjd", "kkkkkkkkknk", "rggggggggggwg", "nknnnnnnnnnnnn", "vdccccf", "hblbb", "spmm", "shsssssssrssgssdss", "xxxxxxxxxxpx", "xzjmjdclpdtqjhhqm", "qjljz", "ftttr", "krnktrmjvkcqdwm", "nljwhlkpdknfl", "xxxxxxxxgxxxj", "jjhvjjjqjljpjjkjj", "hqwkmmqddbncznm", "lllllllllllllll", "vvfmxfbpzzgmcclhgzzz", "xxxxxxxbjx", "mmkvmgdmm", "qkxlvzxxxxxxxbnx", "rsrrrrbrlrr", "lrndhwcbxf", "qqqqqqqwq", "bxzlpftzfwk", "hlkwkgh", "hmchdm", "ddgbxrfc", "tnmtcbbrwnvwsmfmd", "btpppwcxppqpspppwp", "dddddxzddddddddddxd", "zfvzzzzzzzpz", "zvkzqzzzzzzdzpzzzzz", "nnwnqntnmnn", "blllllllll", "fmffffflrfzfpf", "zqvbjxvjvbvnsznkm", "wqbbpcbb", "jzvwscxzsd", "wwtpn", "mklk", "vvvvvvv", "gnnlclqbnwgngzc", "scdwgdzljgdwmww", "brmnhptdwblr", "tchrszgdttmpvntwdpv", "vjnzjjppjwhjnrpj", "rmjhfhdh", "hbptmhhh", "dszknnnnrbxc", "pkpwdnqvkdxtkppcdtrp", "sjssssshss", "pbtprdj", "nkkkqkkkrkkkkmkvkkmk", "wmwwwzwbwwwswwqswwrw", "dsdzddvddddjldddcxd", "msjrgbrgrlr", "tttltpqtqzt", "nxwnpnk", "jkkkkkjlkzfvxzkk", "mmmmmmz", "rbghdr", "kqqkxkktkxkkk", "jlfttntttdt", "sttttzk", "vvvvvhvvvssvvgvfv", "mmmqm", "rrrqrrrrrrrrrrrpr", "pdrhtt", "zgkxxxxszmhvb", "qqdbzd", "gxgst", "zslgrmgrgjgglg", "qqqrfqqqqqqqqqqqqx", "lrrr", "qnnnfnnn", "wwwwmw", "hhhhhhhhhhhhhh", "kkrcfqxvqhqxzvkkt", "tsrmwckktjnqslm", "rrrrrrrrrrrrrrrrhr", "qqqqqdqqq", "mzxmzpmccmcmmmmmtmm", "cmmmlmmmhmsmmmmm", "blqwsqcjjjfrjrjzwh", "zsmzkcvcmjlsfwfzqmcn", "bgjkglnqnf", "qcxpjnfnnnnnhjvn", "cwzrrpmwwbrkbrrcr", "nhthvnfngd", "xsvrvbvnhbn", "jkjjjmjjjrkjmjv", "kvvvw", "scnfs", "bmff", "rvnfbzklr", "hmbhhhhhhh", "dddlddddddddd", "vxbbp", "jjzjjj", "qqrq", "vssrsswsssqssssvsvws", "czxkgcfwxdxxmxxx", "jdxfccfbvffmh", "rrrrkrrrrj", "kkzklkkk", "hxqfffpfff", "cqtqqqgqkzqqqqqqjwq", "srwdtrr", "ccnc", "ddddfdddgtdg", "kkkkkhlkkkkkkk", "rtgqnqxpnq", "mhnvnjthhfvvwvnzjjrj", "mxzvbwvrqvb", "zzzzzzzzzzz", "bstjbngzfqppdvgwxddk", "tgmvv", "ddsxbxkmxhxrhstz", "wwqrwwrk", "hkkhhhhhmhjhhhhhhhh", "lllqlllllllllcglf", "wwdwwwwjwwwwtwwwwvw", "ggvgg", "qqqqqxqqqhfqsfqqbqvv", "qqqqqqqqtqq", "ssssssssssdssssjs", "gggm", "mmmmmmkmm", "bxfdddsdp", "ddddddwzdddddddddd", "wwwwwfwwfwww", "fqrchrrjwbrdsdtrr", "zzzzzzjzzzzzzzzzztz", "pskwgpmprpspvqpxp", "zzzczzzzzzzzz", "lltlnll", "qvpnxrxprjdtpcspjck", "wzmvxpfhbmjc", "jjktkjjhjjjj", "dddddtdddddddmdddd", "bbjbcbbhbc", "ddddddddddddddjd", "tttttttttttts", "rqrmr", "ggtgggcgjzggtmgtgv", "vmmmdmbmcbmm", "ffffffffft", "mqtfhdbrdsdljkrfnhw", "lqbbcblbbxgbbt", "nsbqqlzszzwtgqz", "lmxqslffrd", "ffflf", "cqfsjlkdfhhp", "kkkkkdk", "nhnnvxnhjnnmnjnrnnkn", "mggzgghgg", "tcknkbkgcvl", "bqqqqqqqtpq", "wwwwwwwwwwwwwwwwwww", "fljgtvt", "dwmsltbqnw", "szpgzxgggggsgr", "pppppppvpcppppppmppp", "pjpnbqk", "zzzzzq", "smmmzgmrjmm", "rkkwvssqdhgxqx", "rrrrrwrr", "gkkjtfztsxrt", "wsrrwwwddwwtwss", "pppprp", "xzjzzzfzzwzzpzdzzz", "fqfhfbqfffvrfsfpf", "gggggggghgggggghg", "pchlvdfmvjrpsdsgw", "rrrrwrdrfrk", "nxmfjhkf", "stmqmrddplzlwzdjbsmk", "jccpcscccpccccxccccf", "ksjjxjmvjwrjlqvxr", "mmrmmmmmjmsmmmcm", "lsrlfgxxcfs", "lrprj", "zdmmxmmjmmm", "xxnxxxxxxxxxxx", "vsqbjvpnnqqnhz", "xghnhqmzf", "rcgphkccb", "wkdwjwwwp", "vvvvsvv", "ccccccccc", "wfbfsfkftffffz", "qqwqqqqqq", "qmrmqkmgw", "pqqqqqcqmlqnqqqjqq", "bxxqrwvmpwwxkrx", "fhlvlffn", "wwwwwww", "nbcbtpb", "xdxxzgx", "llgkthwqdpwcdcptlzp", "xtxgxsftqgccldxc", "xlklt", "mwws", "wwgw", "mgmmmpm", "mwzfmmkfw", "ssssssssgsbssss", "zzvxl", "mmmmmmlmmmm", "brxrt", "hdrjvwv", "bknpftfs", "ppkpfpglfpgpzwvwxt", "cddzdfdd", "pdddd", "cccdccccccccccch", "khmxxwmqwxglf", "qqqq", "whvlvkrknmn", "wwwwkwwwwwwwwwwwwshw", "lgcqwrmggxmbg", "xxxxxxxxnxxmk", "mmmmmmmmm", "dddddddddddddddddd", "sccspkcccbz", "bbnzb", "mmmd", "pmsv", "qttttqd", "bbbbbbbbbbkb", "dlwsgtjdqv", "fxxxxxj", "ppppzlp", "cnnnxgtnwnnnn", "jdddjbpzddpd", "xxxfzfxxxxqxxrxxxxmx", "qqqqqqqqqqcq", "rrrrrrrrrrrrdtnrrrr", "kkkzkkkqkqkk", "mmmmhm", "bbbbbbbbbbbbbb", "mmmmmmmmmmmzm", "jjjfk", "ggggggggggg", "vdzdmdpxdnddxdn", "pmzmmbnmmm", "ppppppzpppppzpzp", "qvfzfsscrthxtwpbkwsd", "xtbdvdlrllvnphbcm", "dbdmwmpnfmnhpmmb", "ppppppppqpp", "kvvqb", "fxrcmjkxknlsn", "wwvwkwt", "hvmwwzrkjvhvjwlsjxv", "dvzd", "mmmmk", "fghg", "mmmmcmmmmmv", "rlngtbbrscwf", "wwwxwwwwwwxwwwqww", "wddddddcdddtd", "fffff", "kkzzgzkc", "zzbzzzzzzvvzvk", "dvvgvvqvtsvvlsmj", "ggggggggg", "jkkkv", "czbfffffffzwd", "wshfbxnfxxxxxqpxxqqx", "gmsqbsx", "hkjkgkwkkkkfnp", "gccccmccc", "rrrrrrkrr", "wrrmrzrrtrrrrr", "stwnclhsss", "lllgbxllr", "dvvjgv", "mrppkm", "llnllll", "dcvvmvvvvcvvvvvvl", "dddzd", "npnnsnlxmxvcnmgnqpns", "llplh", "mgxxzdcbqfglqrzshk", "wswwzlwwwjw", "wwwwpwwwwwwqw", "xgggr", "dlrjpncmsnq", "ttttwtttttttttttttjt", "bfdfr", "pqvrlnp", "knsrhrbcjndmgxhcphjr", "xkkxxxx", "thtjsrptttmmtpbbcctb", "mxcmfbmfxmpmlm", "cccpckwcbgscccccwccc", "rrttgttttttrtnj", "vnnn", "xxzxxxxxxxxjxxxxxd", "vvvvvj", "dqqkqqqqqqqqkphvcgqq", "jjhvjqjbjwwhjkj", "dkrgqfq", "gjjjcbj", "nbqjklnnt", "gzzzzzzzzzzzzzzzz", "qddtjhrlsjkqq", "zndqjhkznkfxkbdn", "vfhvmkvvmvvlhssvvtvv", "zzwzzz", "sssssssshsssssslsss", "fkks", "ttttttttt", "swvsvmjszskdjfp", "nqrb", "rcvrrvlcrrrnrrrkv", "zjqznwzzpzz", "phhhhhhhhhhhhhhhh", "vvbvlvvgvvvvvvxrvvc", "pppsp", "rbdpbbplmqxbbb", "pbbbbbbbbbb", "dddddd", "gqwg", "dddrddqcldbpfc", "chnthxplvnnvcxdwj", "cnnctbgrvgflcccsc", "nnnnnnngndnnnn", "cjqpzzz", "zjhzkzhkzzwzzqmslz", "mmmmmmmmmmmgmmxmmmm", "jxfxxxxsqtmkd", "gsrrwrbrrrrjrmndrrrq", "bbbbqbpbbqb", "qqqqqqqqqqdq", "hhhhhhhgvrhhh", "lxlrfcnnlllllwvcllb", "rppf", "wfwrcwffffkfnnfffl", "hhhhzhhhhhh", "qqpdljq", "kfwnkmkkkkkk", "prqr", "pppppppppp", "cccctccccpccccctccwc", "lqfrfkgtvrzb", "gglv", "zhzcz", "ppgpp", "qtmqqvkq", "ksrnnnbsjls", "zrlccsztzzzzzzh", "sssssssss", "zzvzzzzzzzqzzz", "wwwzww", "ssssssskssszstnsssss", "kkkkkknpkkkkdkk", "qnstqt", "qqqbq", "kkzpptpj", "cccnqhckxhcxckmffbv", "llpllcllllllzplhglz", "jjjjjjjjrjj", "lmllllln", "dddldddkdd", "sdkgmrdmmsxjcfmcwdwv", "kkbkkk", "bzbrbngbh", "mdhdddpddddddkddgddj", "zjmplf", "xksxrx", "wwwwwwwwwmxwzw", "vvvdvvvvvpvv", "bwxxq", "ntkklsjkqvwvkxkqtkwr", "gcjc", "hppwshwhnbhk", "nnnnnnnnnnnnnnnnnnn", "qwwvfxwpwlwwwx", "wdlmtbhkfnb", "zzjqjkzblzzmfkzzz", "svgsfssqssns", "ddddddddddqddc", "txxxrxzdxxxxxvhxxx", "rllvllwxllkl", "ccccccccccccccccccs", "llllsllllrx", "nnnln", "frmkkz", "tlmj", "mmmvvm", "kkkkmbkgkkkkkkkkmk", "hhhhhhhhrhhhhhjhhhh", "xnnjnd", "kxkkkrxkvrkq", "rccbm", "ddldddrdkp", "hlpcmhbvzhdhphr", "mtmmvm", "xmjmmm", "qxmwmmbrdtxtqwcxfm", "ppppl", "ssssksssrs", "qnqwxwppmqqqqwlk", "wwwwww", "vvvvvvvvvchvfvp", "zdbzzqmkztzt", "ndwmvdldx", "hhjhqhhmpfzjvgmh", "mmmcmmmcmhqf", "xztkvxxd", "wcnhzvh", "xlgxpbxt", "ktdtdxttgnm", "jjjjjjjjjkjjjjjjqjj", "xxxmxrxxxjxxcwxx", "wcpwhfzwwcwj", "wnfgxnnsvknngm", "fkjnlnn", "ffffffffffftffffx", "vvzvv", "rrrrrrrdrrrr", "xwmmmmmmmmmmmmmmmmmm", "nxxxkxx", "ttttttxtt", "ddddhddd", "nqcbtrkvmwskm", "dkdd", "kbrrgxzkbr", "ddddddfddddddddddddd", "kkqkkkk", "lrxkxhxxcxxxxd", "rksdvzsss", "kzhkkqmkm", "hhhhhhhhzjhwcmnhhsh", "fzptx", "zzzzzzzzzhz", "qmswdcdmxqwwqj", "wwwwwnw", "xxnxxxxxxxxxxxx", "gkgpdftggvgchgsgl", "vbvvfgkndklkk", "qmccbcpzc", "srssrssj", "jjjjjjmwjjjhjjq", "hktmzhhhchvhf", "tttttttttttttttttrt", "cvvknfvvv", "xbgccfccqqvbgjtc", "ppxppp", "cgzddqwfkbc", "xttht", "pzvwgwwwwrhwlwwb", "znqhqqqqzqpqqwqqqqq", "wwwwwwwwwwwwwwwbwwvw", "rmmmm", "mfsdnqczrrqrdwvtcs", "vktqrg", "bbbrbbb", "dxrnktlnbqtqt", "jjjjjjjjjjjjj", "lllqfllllllllllpll", "jjjjjjjjjjjjbjz", "fzwzxzzzkzmzzzzlpmn", "nnnnnnnnnnpnn", "mgnncnnnnncnnkn", "rskn", "xggg", "lddgfg", "thcss", "cbzfbqstssqbss", "jbfzzwnqhsgxxvndzlg", "dbqzstvbcxgncgszp", "gfklpbfkbbn", "mslxkdsrtgss", "dxxgd", "npgnrbgnzr", "mtzjrkmgfqmjbjhg", "jjjjjjjjjjmvjjjjmj", "srpckj", "thtt", "gbrl", "phfppphpdptrxpwpzvcr", "mvkwmtkhm", "mmmmmmsmmmmmrtmm", "ffffffffffffffffffff", "hqhhhbhhhh", "vjzqgvfqkrwtnldkcb", "dzpptzzztzfg", "brwcfcw", "nnnnnnnnnnn", "bbbbmbbbrwhbbbb", "pppppgj", "ttttwtttt", "vfvvvvvvvvvvvvvvvvvv", "ppbpdppppdpppplzqg", "dddfdd", "xbvmnmvmpsmfvpdzh", "bbbbbbbbbxbbbbbbbbl", "bgglftqqt", "nzzfgzzzzzzkzzztf", "pxrqdmrz", "thttttrtt", "ddddddkddddddjd", "hsrsr", "xwxxxjcxxxxxnxxxxs", "xdmxqxxgxxxxzxxlx", "wfwwwwjwwwwwwww", "ldrqmvfpkrtrtqkcvtc", "ggggggggdgg", "hhhhhh", "nznxxfdnnkrlnnfnnn", "zgdzqztv", "gcwsjjvnbnpkzncjlw", "ddbg", "tpntttttttttftrrtt", "crrrr", "rmddspmddz", "wpbwzswqtwpwxmtpj", "nnrnznjnncdnn", "bggggggggg", "hzltbtqgwxbbxb", "hqbz", "ffffffwfffffd", "srrrj", "fcffff", "xmnhmbzlxvsmrffskl", "tttgnxmtsdttttt", "lplg", "lggggggvggggggggw", "vvvvvvvvvvwvvv", "lppspptpp", "zcpfqphgbppvcfmz", "vvcvvzvvkv", "ctggcsxg", "sstsfjssssss", "zzzzzzzzzzzzz", "crrrrrcrrs", "bbbbbbbbbgblbvb", "qttqpfxmlf", "dddddddddddddgd", "wtchnbbwkmzsmrkk", "nnnznnlnhnnwnznnnnn", "ffrffffrtsndc", "dmtwqmccltqrvkntft", "fdnnslrfdv", "txdtlrtbxrrxdsmrr", "ljdgff", "fddfffltfh", "mjgjrgkjdj", "mlbljhzn", "slnrbjgr", "lcxxccpcbvgdccgccccp", "vvrnlvvvvvvsvvvsvvvv", "nkkkkxk", "rqqw", "ppppppdkprppp", "ddddddddddddddwddddd", "nnnnnnnnnnnnnnnnlj", "ktbfplppnp", "xqpvxrm", "sldflbxpdlltzlpjpml", "tttvtttttttttt", "xxxxxxxxxxxjxxxgxxdx", "hhjdqvzmhxtkbbcptshb", "gggggggggwgggdngg", "jjjjjjjjwjjjjn", "wwwcxxwwzrwwxww", "vtxtlxjqrfplw", "xqfdfzrxrnkwv", "nqkqqqqq", "lhlmklllllgjll", "jwtkk", "dvdjdddhdddddd", "lllfslkltllqdrllxllv", "rwplctrrrvpd", "xdxxjddmcccmxxx", "cccccjcjkcctcjc", "gcpkqzgqwlznmqsmgxc", "ttttttwtstttttwttttt", "zkqdtclhmlpfd", "jdjjjgjjjjjjjjcjjgj", "hsgvzlktmzqhhw", "bsbbbbbbbbbbd", "zzsz", "bcnrdgsfqnwqgdgmctq", "qqqqqtcqqqqhzcvqfqr", "rwww", "tfhppjcrzchjhhrcnt", "wwwwwwwwwwwwwwwwswww", "fsffffffp", "jcccfrzkgbzpmdwfvc", "ffnfffvqff", "bbtb", "xgxxxgxr", "crzvxfznvlx", "nkkklkkvkkkkkxkkkkkk", "mmzmwmmmm", "brbqgk", "qnmkktjgrkfqrzkkk", "plllklfcllzvll", "lmmmb", "kqkk", "kkkkkjkkkjkkkwk", "nrwlrtkrkvtxwpr", "kghdmcvswxbvtbjhdwb", "fnnhdnnnnnj", "bqbrbtbbsbbtgzgbb", "fffffffffffffffffff", "hhhhhhhhhhh", "pwpfrbgfzqpghs", "ggggg", "bcccccpcccccccc", "vppzffvnffkfq", "vfffxfff", "jjjjjjjjljjjjjj", "ffhf", "mmmmmkmcmmmmm", "ccccccqccnsncccxkccc", "wwwwwwwwww", "llrkgsvwkcmphp", "sssssspsssfsts", "gssszgscsqfkssqsj", "jjjjsjjjjjjrjjjjzp", "wqqqqqqvqq", "kffvfffdffsff", "ddddbdddddd", "wbdxrddtnrddddddg", "xggxnfpcxxxdxxsd", "pppppppppppjppppkp", "tccmxmmm", "vmspgmlzzqppfrpggglp", "njnlcwlzdwwdvvgrfxtf", "fmftfd", "pvzzz", "mmmmmmmmmmmmgmmxmz", "pxzzz", "bbbbbbbbbd", "vvvwvvvvvvvvvvvrrv", "jxlqrnngfghxfzfp", "xxxxxxxxxxxmgxxxxhx", "ccccccpccccctccc", "ccccccccccvc", "tttthtttttttttttzsl", "wchwdrftbdhhww", "kzrrzr", "rrrrrrrlpzrvtrxw", "tttttlttttttt", "wwsww", "cccccccxc", "hphhhhvtxjrndzhh", "jjvwsrkmjjqjdjjpsf", "mtxqkzpkdkfkp", "bbbbsbbbbzbbbbbb", "qhhlshhhh", "ljbllllljlllllzrljl", "zzlz", "wwnww", "cbbbbbbbbpbjbbvgb", "xdxxxxxxxdxz", "nvnvzchcdfpnmnnsrnrn", "bbnpxbb", "gdkgsxqkbw", "fxkgm", "zzgzwzzxxn", "hdqmdk", "gnjqjctrrrvnjjvxgmx", "cfdwvpxvvvpvvj", "wtkprnmshmmmqtmzqq", "jjwjv", "xtfjvtttwtvttxtt", "bbbb", "ffffffqdfffffff", "ddddmp", "nnnnnnnnnmnnnnnnnnnn", "xxxxxxxxkx", "cccccccccb", "wwwwwwwwwwwwwwwwwwmd", "zhhhwnqnhhhhhghhvt", "zzzzqzzzlzzzzzzzzk", "hhvfjhrghhhhhthfhhhh", "chgc", "jjjjjjj", "rzzzzzzszzb", "ttttttttmt", "bgggng", "mcdcrcchsdccgtbj", "rrjwgftffmnfm", "rrgrrrrrrbrcrrrbrrrr", "hxhxhghhhhhhhhhhhwh", "nnjnznnnngnnqsnx", "zfwklgrdnjtxj", "bgrbbjf", "nlqn", "mslvj", "cccccccccccccdcccccc", "ggxtgggjcgggggggwggg", "llvhfwhlwztxpdh", "dcdzcccgm", "qqqqqqqqqqqqqqjqqqqq", "zdqw", "hqqqqqqqjfqqqmnlbqqq", "rqqklqfqqqbqhq", "dlmz", "xhnggglggqggqggqgz", "djjjjjjjjjjjj", "qqrqqq", "xdlxngttnlmjb", "bbbbbbzbtb", "jbbtb", "qzzzztzbzzzzzkzzzzz", "pjjwpw", "qqxqqqtqqpnm", "fffffdff", "pjjjjcjxjbjjj", "tfrjqdtkcjcjkcwn", "cpptjkpf", "pggggggggvg", "lbjbbbzbb", "mmmtmmm", "hwpkjdwzpwwwkcsw", "mbkskbpbkr", "qqqcqqqpqqqqqlqjqq", "rlxrrrlrgjkr", "kbkkkkfksmkqgkrk", "lwll", "xqxlcb", "sssssssp", "mmmmmmmrmm", "lnllllzlsl", "zzzwzzzq", "hqdflnll", "jvvzczgrv", "zhzzzdzzzzzzzqzp", "dddcdddddd", "ssssgsshss", "cccc", "hhhhhhhhhhnhhhhhrhh", "ndnlnnnnnz", "hppzpxprfvrpppphpp", "xwvqdfqmpbzvbgbtt", "qqqqqqqn", "mfmmmfmmmmmbmmn", "bgbpr", "fnbbpmffjphv", "nnshthh", "cccwccccccccc", "hppnmppmpppppwphpc", "ggggmggdg", "fdwjpkdrbfff", "lmvcldnwwzjznzsctzvv", "bbbbbbbbxbbbbbbbb", "whkjzsvrr", "hrdzhrhrxdnrhfhhhh", "nnvqbnbhwqfr", "qndbrqxtkqq", "rrrjsrlrrg", "jhzzzzzzzzzzzzzwz", "wstfcqqsbqq", "bggg", "xrgvsjvwjrd", "bbjbbbbbbblbpbbbbb", "hbhdqphmp", "dvddddddddddddmdddl", "vtbclnppvvqxljk", "xkmksddkg", "zzzzqtzzzqmzpzz", "xxxqxxxxxxxxxxxxxt", "fffffc", "vvvvvvwvvvvvvvvvvv", "ndqxfrbtfmptcrf", "mszzz", "nnnnnnnnnnn", "ftfdl", "tnjgfppdhswwdhclxmn", "lllvlllglllfll", "ppppppppmpppppppppp", "sccccqxwscvbmcccxcz", "wxxxxxxx", "kdkkkmvgvmsfswvbtsc", "kkkkkkkkkkkkkkkkkkdk", "ccccchcjd", "vmpvvmgjkfsv", "ssssslsssqnjssssss", "htvqnhgbszh", "ptdrlpnnjrpppjrgp", "wgxwwtntwrsczwwrjz", "bbbqbbbbbb", "gxxx", "fntbvdtjmtsktztpdgkt", "fffbff", "mmmmmlgmmmmmmwlmmmm", "zknzsdlzzszzzzzxzz", "cccccccccccccccccvc", "bwgvvxvvv", "kkkkkxkdkkk", "xfsxxd", "hhxhrrlrbwwnjkkwb", "rnxrrrrrrrrlrrr", "lllllwllzlll", "llllllllll", "cccccccdtccrcclcccc", "tttttttttt", "nnkn", "xqvqlsjlgl", "kkkrrkn", "mdrdmddpmd", "ccccch", "mmfmcmm", "gxxdzbxzxxxx", "rmtkgcrvlrg", "cmrrwrzv", "dcjlzl", "bbbbbbrpbmbmnbbb", "ssssws", "sllwlvjl", "bbxlbbb", "cczpq", "vqgnlzbbkjkljk", "hhfhhhhhhhhhhhh", "kfkkrx", "qqqqqqr", "dsqllgzl", "rrrrrrrrxr", "mvvh", "ppppppp", "xxxxxxxxxxxxxxxxkxx", "bbbbcbbpb", "jjjjcpjjjwjjjjjjjj", "rscprvknxrgxqzsrs", "wwgwwwhcwwwwwww", "blkb", "zrrrhlt", "wcmmmfh", "mctnxtktrsj", "wcccc", "sjjjjjjjjjjjtjj", "fztxkwhrrxnnn", "rrqrrrr", "qqqqvqqq", "ttvpttkptthtttrcj", "znjqsvpstfjph", "llllllnl", "vwltcctcmcdccrqdccwc", "bfkxfrsznfkdzpjmbp", "qqqqqqqqqqqvqqqq", "tttttbttktt", "ccdczcvccvclcccvkccb"};
        if (prvnici.length + druzici.length + pismenci.length + asswordi.length != 4000) {
            throw new Exception("fucked up.");
        }
        int kuntr = 0;

        String[] bs = "banan".split("");
        //while (true){
        //    System.out.println(bs[kuntr]);
        //    kuntr++;
        //}


        for (int takneco = 0; takneco < prvnici.length; takneco++){
            if (fuckifiknow(prvnici[takneco], druzici[takneco], pismenci[takneco], asswordi[takneco])) kuntr++;
        }
        System.out.println(kuntr);
    }

    //true if splňuje podmínky
    public static boolean fuckifiknow(int first, int second, String letter, String assword) {
        String[] newshite = assword.split("");
        return (newshite[first-1].equals(letter) ^ newshite[second-1].equals(letter));
    }
}
/*








































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































 */